repos:
-   repo: https://github.com/ambv/black
    rev: 22.3.0 
    hooks:
    - id: black
      language: python
      types: [python]
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
